---
abstract: 'a fast HTTP POE component'
author:
  - 'Chris Williams'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300032, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Curl-Multi
requires:
  HTTP::Headers: 5.810
  HTTP::Request: 5.811
  HTTP::Request::Common: 5.811
  HTTP::Response: 5.813
  HTTP::Status: 5.811
  POE: 1.312
  POE::Component::Server::TCP: 0
  URI: 1.37
  WWW::Curl: 4.15
resources:
  homepage: https://github.com/bingos/poe-component-curl-multi
  repository: https://github.com/bingos/poe-component-curl-multi.git
version: 0.02
